pragma Singleton
import QtQuick

// Tokens de color de la app. Un mismo color hexadecimal puede aparecer en
// varios tokens cuando cumple roles de diseño distintos (p.ej. blanco de
// tarjeta vs. blanco de fila de tabla): eso es intencionado, no duplicación.
QtObject {
    readonly property color bgApp: "#eef2f0"
    readonly property color bgNav: "#123f31"
    readonly property color bgNavItemActive: "#1a7a5e"
    readonly property color bgNavItemHover: "#1a5a45"
    readonly property color bgSurface: "#ffffff"
    readonly property color bgBrandStrong: "#14523f"
    readonly property color bgTableRowPrimary: "#ffffff"
    readonly property color bgTableRowAlt: "#f7faf8"
    readonly property color bgTableRowEmphasis: "#e3efe9"
    readonly property color bgTableRowSeparator: "#dde9e2"
    readonly property color bgAccentTint: "#eef5f1"
    readonly property color bgInput: "#fffbe8"
    readonly property color bgInputInvalid: "#fdecea"
    readonly property color bgInputPressed: "#e0d6ac"
    readonly property color bgDropdownItemHighlighted: "#eef0c9"
    readonly property color bgRowCardDefault: "#f4f8f6"
    readonly property color bgRowCardEmphasis: "#bfe2cf"
    readonly property color bgButtonPrimaryDefault: "#1a7a5e"
    readonly property color bgButtonPrimaryPressed: "#0f5a43"
    readonly property color bgButtonSecondaryDefault: "#1a5a45"
    readonly property color bgButtonSecondaryPressed: "#0e3226"
    readonly property color bgButtonGhostDefault: "#ffffff"
    readonly property color bgButtonDangerDefault: "#a33b2e"
    readonly property color bgButtonDangerPressed: "#8a2a1f"
    readonly property color bgSwitchTrackOn: "#1a7a5e"
    readonly property color bgSwitchTrackOff: "#c9d6cf"
    readonly property color bgSwitchThumb: "#ffffff"
    readonly property color bgTransparent: "transparent"

    readonly property color textOnDark: "#ffffff"
    readonly property color textOnDarkMuted: "#7fae9c"
    readonly property color textOnDarkSecondary: "#cfe8de"
    readonly property color textButtonPrimary: "#ffe9a8"
    readonly property color textHeading: "#14523f"
    readonly property color textSecondary: "#3c4a46"
    readonly property color textPrimary: "#1e2b28"
    readonly property color textNegative: "#a33b2e"
    readonly property color textMuted: "#6b7a76"
    readonly property color textFaint: "#7a8985"
    readonly property color textInvalid: "#c0392b"
    readonly property color textWarning: "#a15c00"
    readonly property color textButtonGhost: "#1a5a45"

    readonly property color borderSurface: "#dde5e1"
    readonly property color borderDivider: "#dde5e1"
    readonly property color borderNavDivider: "#2b6a52"
    readonly property color borderButtonPrimary: "#2b8a6a"
    readonly property color borderButtonSecondary: "#2b6a52"
    readonly property color borderButtonDanger: "#c24d3c"
    readonly property color borderButtonGhostDefault: "#c9d6d0"
    readonly property color borderInteractiveHover: "#1a7a5e"
    readonly property color borderInputDefault: "#e0d6ac"
    readonly property color borderInputInvalid: "#c0392b"
    readonly property color borderTableGroupEnd: "#8fb3a3"
    readonly property color borderRowCardDefault: "#d5e6dc"
    readonly property color borderRowCardEmphasis: "#7fbb9b"
    readonly property color borderAccent: "#1a7a5e"
    readonly property color borderSwitchTrackOff: "#a8b8b0"

    readonly property color iconOnDark: "#ffffff"
    readonly property color iconAccent: "#ffe9a8"
}
